### ISSUE TITLE
zlib error

### ISSUE THREAD

**Issue by sscoster** [nunofonseca/msi#4]
When running ./scripts/msi_install.sh -i ~/msi, during the execution of install_deps.sh, http://zlib.net/zlib-1.2.11.tar.gz is not found. The file has been moved to https://zlib.net/fossils/zlib-1.2.11.tar.gz.

**Comment by nunofonseca** [comment]
Thanks for reporting the issue. The problem should be fixed in the latest release.
Cheers.
