### ISSUE TITLE
MSI with Illumina paired end data

### ISSUE THREAD

**Issue by Lveillat** [nunofonseca/msi#6]
Hello,
Is it possible to use the MSI tool with Illumina paired-end data? If so, how should we proceed ?
Thank you.

**Comment by nunofonseca** [comment]
Hi, 
MSI was designed for long reads therefore it will not work with paired-end data.
However, if you really want to try MSI on your data then the paired reads would have to be merged before being provided to msi (as single reads). There are several tools available to merge reads: https://www.biostars.org/p/225683/
Cheers.
